server:
  port: 8180

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8182/eureka/}
    register-with-eureka: true
    fetch-registry: true
  healthcheck:
    enabled: true

spring:
  cloud:
    discovery:
      locator:
        lower-case-service-id: true
        enabled: true
    gateway:
      routes:
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/orders/**
        - id: restaurants-service
          uri: lb://RESTAURANTS-SERVICE
          predicates:
            - Path=/restaurants/**
        - id: drivers-service
          uri: lb://DRIVERS-SERVICE
          predicates:
            - Path=/drivers/**
  application:
    name: gateway

info:
  app:
    name: ${spring.application.name}
    version: @project.version@


logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE